[package]
name = "flare-commander"
version = "0.1.0"
description = "A Tauri App"
authors = ["Christian Binzer"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "flare_commander_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
cloudflare = { version = "0.13.0" }
tauri = { version = "2.2.3", features = [] }
tauri-plugin-opener = "2.2.4"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.136"
reqwest = "0.12.12"
tokio = { version = "1.43.0", features = ["macros"] }

[dev-dependencies]
wiremock = "0.6.2"
